version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: antivirus_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456P@$$
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  python-app:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: antivirus_db
      DB_USER: postgres
      DB_PASS: 123456P@$$
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python main.py

volumes:
  postgres_data:
